language: generic
sudo: required
dist: xenial
matrix:
  include:
    - os: linux
      env: SWIFT_VERSION=4.0.3
    - os: linux
      env: SWIFT_VERSION=4.1
    - os: osx
      osx_image: xcode9.2
      #env: SWIFT_VERSION=4.0
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)" ; fi
script:
  - swift build
  - swift build --configuration=release
  - swift test