os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.2
env:
  matrix:
    - SWIFT_VERSION=3.0.2
    - SWIFT_VERSION=3.1
install:
  - if [[ "$SWIFT_VERSION" != "3.0.2" ]] || [[ "$TRAVIS_OS_NAME" != "osx" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)" ; fi
script:
  - swift build
  - swift test