version: 2
jobs:
  mac-swift4.1:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux-swift4.1:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux-swift4.2:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run: swift build
      - run: swift test
workflows:
  version: 2
  build_and_test:
    jobs:
      - mac-swift4.1
      - linux-swift4.1
      - linux-swift4.2

